plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - advanced/characterization.md
  - gitHubAdmin/overview.md
  - gitHubAdmin/people.md
  - gitHubAdmin/repositories.md
  - gitHubAdmin/settings.md
  - gitHubAdmin/teams.md
  - quickStart/codingWorkflow.md
  - quickStart/gitHubDesktopTut.md
  - quickStart/programingQuickStart.md
  - quickStart/setupGitHub.md
  - quickStart/setupGitHubDesktop.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - index.md
  - README.md
  
theme: jekyll-theme-slate
