plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - advanced/characterization.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - detailedSetup/genericVSCodeSetup.md
  - Documents/TheBasicsOfGitHub.md
  - gitHubAdmin/orgManagement/orgDiscount.md
  - gitHubAdmin/orgManagement/orgOwners.md
  - gitHubAdmin/orgManagement/teamCleanup.md
  - gitHubAdmin/overview.md
  - gitHubAdmin/people.md
  - gitHubAdmin/quickGuides/membersQuickSetup.md
  - gitHubAdmin/quickGuides/orgMaintenanceGuide.md
  - gitHubAdmin/quickGuides/repositoryQuickSetup.md
  - gitHubAdmin/repositories.md
  - gitHubAdmin/settings.md
  - gitHubAdmin/teams.md
  - hardware/statusLights.md
  - index.md
  - java/JavaCheatSheet.md
  - legacyTutorials.md
  - quickStart/codingWorkflow.md
  - quickStart/gitHubDesktopTut.md
  - quickStart/introToGit.md
  - quickStart/programingQuickStart.md
  - quickStart/setupGitHub.md
  - quickStart/setupGitHubDesktop.md
  - README.md
  
theme: jekyll-theme-slate
