matrix:
- name: Markdown
  aspell:
    lang: en
  dictionary:
    wordlists:
    - .github/workflows/config/.wordList.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown: Null
  - pyspelling.filters.html:
    comments: false
    ignores:
    - code
    - pre
  sources:
  - '**/*.md'
  default_encoding: utf-8
